Improve performance when mergin overlapping timed data series
mbeckersys/MavLogAnalyzer pull request #3
Opened 2017-07-12 09:32 UTC by Mike-Bal

Instead of inserting each value into the original data series individually (which requires shifting the data around each time), both data series get merged into a newly allocated buffer and the result is then copied back into the original one (In total O(N+M) instead of O(N*M)).

On the last set of flight data this improved loading time on my machine from ~8min to ~20s. Should work with pre c++11 compilers, but I only tested it with MSVC2017

2017-07-12 19:51 UTC, mbeckersys commented on src/data_timeseries.h
> +            //merge time and data arrays into one array (SOA to AOS) for both our data and other data
What do "SOA" and "AOS" stand for?

2017-07-12 20:01 UTC, mbeckersys commented
I like this commit, but unfortunately this does not build under g++ 4.9.2.

There are two problems with this:
 1. Extended initializers (e.g., line data_timeseries.h:545) are only available in C++11. This would force us to compile the entire application with a C++11 compiler, which is untested.
 2. This code is trying to instantiate a template in a local class (e.g., data_timeseries.h:543, which is forbidden (14.3.1[temp.arg.type]/2.). That might be allowed in C++11, though. 

It might build with --std=c++11 flag, but this is a bigger change for which I'd like to open a separate branch.

2017-07-12 20:05 UTC, mbeckersys requested changes
Needs fix (we want C++98 in this branch)

2017-07-12 20:05 UTC, mbeckersys commented on src/data_timeseries.h
> +                own[cnt] = TimedData{_elems_time[cnt], _elems_data[cnt]};
C++11 initializer

2017-07-12 20:05 UTC, mbeckersys commented on src/data_timeseries.h
> +                others[cnt] = TimedData{src->_elems_time[cnt] - dt_sec, src->_elems_data[cnt]};
C++11 initializer

2017-07-12 20:05 UTC, mbeckersys commented on src/data_timeseries.h
> +            std::vector<TimedData> own(_elems_time.size());
Using a local class to instantiate a template. Forbidden in C++98.

2017-07-12 20:05 UTC, mbeckersys commented on src/data_timeseries.h
> +            std::vector<TimedData> others(src->_elems_time.size());
Using a local class to instantiate a template. Forbidden in C++98.

2017-07-12 20:05 UTC, mbeckersys commented on src/data_timeseries.h
> +            std::vector<TimedData> merged(total_size);
Using a local class to instantiate a template. Forbidden in C++98.

2017-07-12 22:08 UTC, Mike-Bal commented
> This code is trying to instantiate a template in a local class (e.g., data_timeseries.h:543, which is forbidden (14.3.1[temp.arg.type]/2.). That might be allowed in C++11, though.

Sorry, didn't know about that. I could put the class definition into the (private) class scope

> Do you have any comparison of memory usage?

No, but the lifetime of the additional vectors is limited to the scope of the function, so overhead is bounded by the length of a single data sequence + length of new data, times the size of time stampe + data item:

So `< 2* ( M + N )*( sizeof( double ) + sizeof( T ) ) + (additional capacity in the  vectors)` 

So if the largest series has 100'000 samples (existing + new) it should be less than 10MB

2017-07-12 22:09 UTC, Mike-Bal commented on src/data_timeseries.h
> +            //merge time and data arrays into one array (SOA to AOS) for both our data and other data
Struct of Array / Array of Struct

2017-07-20 14:00 UTC, merged

2017-07-20 14:00 UTC, mbeckersys commented
Good stuff, thank you!